repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.2.1"
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/grantjenks/blue.git
    rev: "v0.9.1"
    hooks:
      - id: blue
  - repo: https://github.com/commitizen-tools/commitizen
    rev: "v3.14.1"
    hooks:
      - id: commitizen
        stages: [commit-msg]
